### PR TITLE
added the notebook links in the table

### PR DESCRIPTION
**Pull request by deepu1067**

### CODE REVIEW

**Review by FahimFBA — CHANGES_REQUESTED** [review]
Sometimes, larger notebooks fail to display in the browser. Therefore, I think it would be a good idea if we keep the original notebook location and [nbviewer](https://nbviewer.org/) location side by side in the table. 

What do you think, @IsratIJK ?

**Review by IsratIJK — CHANGES_REQUESTED** [review]
I also think that including the [nbviewer](https://nbviewer.org/) link side-by-side is a good idea. Therefore, others will have direct access to our notebook file and they can also view the notebook directly without downloading it if they want (if they face difficulties in viewing them directly on GitHub).

**Review by deepu1067 — COMMENTED** [review]
added the nbviewer link.

**Review by FahimFBA — APPROVED** [review]
Looks Good to Me!

**Review by IsratIJK — APPROVED** [review]
Review has been completed from Israt

**Pull request merged**
